language: csharp
dotnet: 2.1.4
mono: 5.10.0

branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/

os:
  - linux
  - osx

git:
  depth: false

install:
- nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
- msbuild src /nologo /m /v:quiet /t:restore

script:
- msbuild src /nologo /m /v:minimal /t:build,pack
#- dotnet test --no-restore --no-build src/HttpClientEcho.Tests -f netcoreapp1.0
- dotnet test --no-restore --no-build src/HttpClientEcho.Tests -f netcoreapp2.0
- mono testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe bin/HttpClientEcho.Tests/Debug/net461/HttpClientEcho.Tests.dll
